image: obgm/dcaf:build-env

stages:
  - build
  - test

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - ./autogen.sh
    - ./configure --enable-tests
  script:
    - make
  artifacts:
    paths:
      - tests/testdriver
      - am/dcaf-am
      - examples/dcaf-client
      - examples/s
    expire_in: 1 week
  cache:
    paths:
      - .libs

# run tests using the binary built before
test:
  stage: test
  script:
    - tests/testdriver
